INSERT INTO public."Country" (id, name) VALUES (1, 'Slovenia');
INSERT INTO public."Country" (id, name) VALUES (2, 'United States');
INSERT INTO public."Country" (id, name) VALUES (3, 'France');
INSERT INTO public."Country" (id, name) VALUES (4, 'Japan');
INSERT INTO public."Country" (id, name) VALUES (5, 'Canada');
INSERT INTO public."Country" (id, name) VALUES (6, 'Spain');
INSERT INTO public."Country" (id, name) VALUES (7, 'Italy');
INSERT INTO public."Country" (id, name) VALUES (8, 'Australia');
INSERT INTO public."Country" (id, name) VALUES (9, 'Germany');
INSERT INTO public."Country" (id, name) VALUES (10, 'Austria');
