INSERT INTO public."Region" (id, name) VALUES (1, 'Gorenjska');
INSERT INTO public."Region" (id, name) VALUES (2, 'Primorsko-Notranjska');
INSERT INTO public."Region" (id, name) VALUES (3, 'Pomurska');
INSERT INTO public."Region" (id, name) VALUES (4, 'California');
INSERT INTO public."Region" (id, name) VALUES (5, 'Texas');
INSERT INTO public."Region" (id, name) VALUES (6, 'New York');
INSERT INTO public."Region" (id, name) VALUES (7, 'Île-de-France');
INSERT INTO public."Region" (id, name) VALUES (8, 'Provence-Alpes-Côte d''Azur');
INSERT INTO public."Region" (id, name) VALUES (9, 'Kanto');
INSERT INTO public."Region" (id, name) VALUES (10, 'Kansai');
INSERT INTO public."Region" (id, name) VALUES (11, 'Ontario');
INSERT INTO public."Region" (id, name) VALUES (12, 'Quebec');
INSERT INTO public."Region" (id, name) VALUES (13, 'Andalusia');
INSERT INTO public."Region" (id, name) VALUES (14, 'Catalonia');
